### ISSUE TITLE
Cannot build for Android

### ISSUE THREAD

**Issue by arelstone** [taskrabbit/react-native-zendesk-chat#87]
I cannot build for android using version 0.4.0.

I get the error below:

####  Steps
1. `npm install react-native-zendesk-chat`
1. `npm run ios` everything works find
1. `npm run android`
1. tried to run `react-native link react-native-zendesk-chat --platforms android` didn't do the trick either. Gives the same error as without running `link`

#### React native info:
```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 158.17 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 28, 29
      Build Tools: 23.0.1, 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^3.2.1 => 3.2.1 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

####  Error
```
error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.zendesk:chat:2.2.0.
     Searched in the following locations:
       - file:/Users/_________/.m2/repository/com/zendesk/chat/2.2.0/chat-2.2.0.pom
       - file:/Users/_________/.m2/repository/com/zendesk/chat/2.2.0/chat-2.2.0.jar
       - file:/Users/_________/Projects/mobile/node_modules/react-native/android/com/zendesk/chat/2.2.0/chat-2.2.0.pom
       - file:/Users/_________/Projects/mobile/node_modules/react-native/android/com/zendesk/chat/2.2.0/chat-2.2.0.jar
       - file:/Users/_________/Projects/mobile/node_modules/jsc-android/dist/com/zendesk/chat/2.2.0/chat-2.2.0.pom
       - file:/Users/_________/Projects/mobile/node_modules/jsc-android/dist/com/zendesk/chat/2.2.0/chat-2.2.0.jar
       - https://dl.google.com/dl/android/maven2/com/zendesk/chat/2.2.0/chat-2.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/zendesk/chat/2.2.0/chat-2.2.0.jar
       - https://jcenter.bintray.com/com/zendesk/chat/2.2.0/chat-2.2.0.pom
       - https://jcenter.bintray.com/com/zendesk/chat/2.2.0/chat-2.2.0.jar
       - https://jitpack.io/com/zendesk/chat/2.2.0/chat-2.2.0.pom
       - https://jitpack.io/com/zendesk/chat/2.2.0/chat-2.2.0.jar
       - https://maven.google.com/com/zendesk/chat/2.2.0/chat-2.2.0.pom
       - https://maven.google.com/com/zendesk/chat/2.2.0/chat-2.2.0.jar
     Required by:
         project :app > project :react-native-zendesk-chat
   > Could not find com.zendesk:messaging:4.3.1.
     Searched in the following locations:
       - file:/Users/_________/.m2/repository/com/zendesk/messaging/4.3.1/messaging-4.3.1.pom
       - file:/Users/_________/.m2/repository/com/zendesk/messaging/4.3.1/messaging-4.3.1.jar
       - file:/Users/_________/Projects/mobile/node_modules/react-native/android/com/zendesk/messaging/4.3.1/messaging-4.3.1.pom
       - file:/Users/_________/Projects/mobile/node_modules/react-native/android/com/zendesk/messaging/4.3.1/messaging-4.3.1.jar
       - file:/Users/_________/Projects/mobile/node_modules/jsc-android/dist/com/zendesk/messaging/4.3.1/messaging-4.3.1.pom
       - file:/Users/_________/Projects/mobile/node_modules/jsc-android/dist/com/zendesk/messaging/4.3.1/messaging-4.3.1.jar
       - https://dl.google.com/dl/android/maven2/com/zendesk/messaging/4.3.1/messaging-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/zendesk/messaging/4.3.1/messaging-4.3.1.jar
       - https://jcenter.bintray.com/com/zendesk/messaging/4.3.1/messaging-4.3.1.pom
       - https://jcenter.bintray.com/com/zendesk/messaging/4.3.1/messaging-4.3.1.jar
       - https://jitpack.io/com/zendesk/messaging/4.3.1/messaging-4.3.1.pom
       - https://jitpack.io/com/zendesk/messaging/4.3.1/messaging-4.3.1.jar
       - https://maven.google.com/com/zendesk/messaging/4.3.1/messaging-4.3.1.pom
       - https://maven.google.com/com/zendesk/messaging/4.3.1/messaging-4.3.1.jar
     Required by:
         project :app > project :react-native-zendesk-chat

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:15)
    at runOnAllDevices (/Users/_________/Projects/mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/_________/Projects/mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at /Users/_________/Projects/mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (/Users/_________/Projects/mobile/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:182:9)
```

**Comment by pistonsky** [comment]
In your `android/app/build.gradle` before the `dependencies` section, add the following `repositories` section:

```
repositories {
    maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
}
```

**Comment by arelstone** [comment]
Thanks @pistonsky adding the repositories, helped.

Did I not read the readme properly or does the readme not mention this?

**Comment by fbartho** [comment]
I'm sorry if it's unclear. This library assumes you're familiar with Zendesk's documentation. 

Linked at the top of the Readme, [android docs can be found here](https://developer.zendesk.com/embeddables/docs/chat-sdk-v-2-for-android/introduction).

**Comment by hakkikonu** [comment]
> In your `android/app/build.gradle` before the `dependencies` section, add the following `repositories` section:
> 
> ```
> repositories {
>     maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
> }
> ```

Thanks!!

**Comment by jvgeee** [comment]
@fbartho this is really something that should be in the readme as a required step for Android, having it as part of the manual setup instructions implies that it's optional if you have autolinking working. It's just as essential as doing `pod install`!
